#!/bin/bash
#
# Enable a site by creating link in sites-enabled to sites-available

# Ensure running as root
if [ "$(id -u)" -ne 0 ]; then
    echo 'This script is designed to run as root'
    exit 1
fi

# Check arguments
if [ $# -lt 1 ]; then
    echo 'Syntax: enable-site <site-name>'
    exit 1
fi

# Determine site information
SITENAME=$1

# Check if link exists
if [ -f /etc/nginx/sites-enabled/$SITENAME.conf ]; then
    rm /etc/nginx/sites-enabled/$SITENAME.conf
else
    echo "Site is not enabled"
    exit 1
fi

# Check that nginx is happy with configuration
nginx -t
if [ $? -ne 0 ]; then
    echo 'Nginx reported error in configuration'
    exit 1
fi
nginx -s reload

echo "Disabled site $SITENAME"

