#!/bin/bash
#
# Install applications on Ubuntu system.

# Ensure running as root
if [ "$(id -u)" -ne 0 ]; then
    echo 'This script is designed to run as root'
    exit
fi

# Ensure we are up to date
echo 'Ensure packages are updated and upgraded'
apt-get -yq update
apt-get -yq upgrade

# Setup time synchronization
apt-get -yq install ntpdate
tee /etc/cron.daily/ntpdate > /dev/null << EOF
ntpdate ntp.ubuntu.com
EOF
chmod 755 /etc/cron.daily/ntpdate
ntpdate ntp.ubuntu.com

# Install packages
apt-get -yq install nginx
apt-get -yq install mariadb-server mariadb-client php7.2-mysql

# Letsencrypt Certbot
add-apt-repository -y ppa:certbot/certbot
apt -y install python-certbot-nginx

