#!/bin/bash
#
# Install applications on Ubuntu system.

# Ensure running as root
if [ "$(id -u)" -ne 0 ]; then
    echo 'This script is designed to run as root'
    exit
fi

# Ensure we are up to date
echo 'Ensure packages are updated and upgraded'
apt-get -yq update
apt-get -yq upgrade

# Setup time synchronization
apt-get -yq install ntpdate
if [ ! -f /etc/cron.daily/ntpdate ]; then
    tee /etc/cron.daily/ntpdate > /dev/null << EOF
ntpdate ntp.ubuntu.com
EOF
    chmod 755 /etc/cron.daily/ntpdate
fi
ntpdate ntp.ubuntu.com

# Install packages
apt-get -yq install nginx
apt-get -yq install mariadb-server mariadb-client php7.2-mysql

# Configure nginx
sed -ri "s/http \{/http \{\n\tclient_max_body_size 50M;/" /etc/nginx/nginx.conf

# Configure php
sed -ri "s/upload_max_filesize.+\$/upload_max_filesize = 50M/" /etc/php/7.2/fpm/php.ini

# Install .NET Core
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
apt-get -yq install dotnet-sdk-2.2

# Letsencrypt Certbot
add-apt-repository -y ppa:certbot/certbot
apt -y install python-certbot-nginx

# Postfix for local smtp server
debconf-set-selections <<< "postfix postfix/mailname string mail.apprange.com"
debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
apt -y install mailutils
sed -i "/^inet_interfaces/c\\inet_interfaces = loopback-only" /etc/postfix/main.cf
sed -i "/^mydestination/c\\mydestination = \$myhostname, localhost.\$mydomain, \$mydomain" /etc/postfix/main.cf
systemctl restart postfix

